# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fait_historique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('date_fait', models.DateField()),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('autre_nom', models.CharField(max_length=30, null=True)),
                ('autre_prenom', models.CharField(max_length=30, null=True)),
                ('arbre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formulaires.Arbre')),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('nb_personnes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[(b'feminin', b'F\xc3\xa9minin'), (b'masculin', b'Masculin')], max_length=8)),
                ('ddn', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mdp', models.CharField(max_length=10)),
                ('adresse', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=60)),
                ('nationalite', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('rang', models.IntegerField(default=0)),
                ('moderateur', models.IntegerField(default=1)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formulaires.Famille')),
            ],
        ),
        migrations.AddField(
            model_name='arbre',
            name='famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formulaires.Famille'),
        ),
    ]
