# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaires', '0002_remove_utilisateur_famille'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='famille',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Formulaires.Famille'),
        ),
    ]
