# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaires', '0003_auto_20161219_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='famille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Formulaires.Famille'),
        ),
    ]
