# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaires', '0005_auto_20170110_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='validation_mdp',
        ),
    ]
