# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaires', '0006_remove_utilisateur_validation_mdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='validation_mdp',
            field=models.CharField(default=b'', max_length=10),
        ),
    ]
