# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaires', '0006_remove_utilisateur_validation_mdp'),
        ('Formulaires', '0005_auto_20170118_1030'),
    ]

    operations = [
    ]
