# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaires', '0007_merge_20170118_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='rang',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
