# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaires', '0010_auto_20170119_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='fait_historique',
            name='type_event',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
