# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaires', '0013_delete_familleblbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fait_historique',
            name='code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
