# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaires', '0014_auto_20170119_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='fait_historique',
            name='for_user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
