# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaires', '0015_fait_historique_for_user'),
        ('Formulaires', '0007_auto_20170120_0833'),
    ]

    operations = [
    ]
