# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaires', '0016_merge_20170120_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recherche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(blank=True, max_length=100)),
                ('rech_pers', models.CharField(blank=True, max_length=10)),
                ('rech_fam', models.CharField(blank=True, max_length=10)),
                ('rech_page', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
