# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaires', '0018_auto_20170120_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recherche',
            name='rech_fam',
            field=models.CharField(blank=True, choices=[(b'rech_pers', b'rech_pers'), (b'rech_fam', b'rech_fam'), (b'rech_page', b'rech_page'), (b'False', b'False')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='rech_page',
            field=models.CharField(blank=True, choices=[(b'rech_pers', b'rech_pers'), (b'rech_fam', b'rech_fam'), (b'rech_page', b'rech_page'), (b'False', b'False')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='rech_pers',
            field=models.CharField(blank=True, choices=[(b'rech_pers', b'rech_pers'), (b'rech_fam', b'rech_fam'), (b'rech_page', b'rech_page'), (b'False', b'False')], max_length=10, null=True),
        ),
    ]
