# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaires', '0019_auto_20170120_1324'),
        ('Formulaires', '0008_utilisateur_photo'),
    ]

    operations = [
    ]
