# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaires', '0020_merge_20170120_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, default=b'', upload_to=b'Formulaires/static/img/'),
        ),
    ]
