# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaires', '0021_auto_20170120_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, default=b'', upload_to=b'img/'),
        ),
    ]
