# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaires', '0022_auto_20170120_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanqueImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, default=b'', upload_to=b'img/')),
                ('photo2', models.ImageField(blank=True, default=b'', upload_to=b'img/')),
                ('photo3', models.ImageField(blank=True, default=b'', upload_to=b'img/')),
                ('photo4', models.ImageField(blank=True, default=b'', upload_to=b'img/')),
                ('photo5', models.ImageField(blank=True, default=b'', upload_to=b'img/')),
                ('photo6', models.ImageField(blank=True, default=b'', upload_to=b'img/')),
                ('photo7', models.ImageField(blank=True, default=b'', upload_to=b'img/')),
                ('photo8', models.ImageField(blank=True, default=b'', upload_to=b'img/')),
                ('photo9', models.ImageField(blank=True, default=b'', upload_to=b'img/')),
                ('photo10', models.ImageField(blank=True, default=b'', upload_to=b'img/')),
            ],
        ),
    ]
