# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaires', '0026_auto_20170120_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BanqueImages',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, default=b'', null=True, upload_to=b'/static/img/'),
        ),
    ]
